### ISSUE TITLE
sheryjs is not working

### ISSUE THREAD

**Issue by aiyan113** [asynchronousJavascriptor/sheryjs#3]
hello sir, great fan of your videos  i was making a website of your recent video and i was using your sheryjs but i dont know why its not working tried everything but its not working for example text animate and image effect and debug panel is also not showing after applying cdn for both css and java script please help me with this.

looking forward for your responce,

thanks.

**Comment by Dharmendra016** [comment]
yes it's not working on my device too .

**Comment by asynchronousJavascriptor** [comment]
we're creating a v2 it's in development currently, almost every issue related to it will be resolved <3
