### ISSUE TITLE
New Update might have Broken SheryJS

### ISSUE THREAD

**Issue by imankush10** [asynchronousJavascriptor/sheryjs#4]
Hello Harsh Sir, I was following your video of Ray Ban landing page and I noticed that the config: {// values} are not working anymore. The effects itself are working but after copying configuration form the debugger, and pasting it as you taught, breaks the whole code. I checked everything commas and all.
Please take a look at this again.

Much Love and Great Respect for the phenomenal work you are doing.

**Comment by its-rio** [comment]
my issue is also similar to this
