### ISSUE TITLE
Shery js is not working

### ISSUE THREAD

**Issue by its-rio** [asynchronousJavascriptor/sheryjs#5]
i apply the effects but when i click to save to clipboard button  don't know but its not copying the code.

**Comment by aiyan113** [comment]
i am not getting debug panel

**Comment by asif-khan-2k19** [comment]
> i am not getting debug panel

You have to paste the scripts in the sequence given below:

    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/gsap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/ScrollTrigger.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/0.155.0/three.min.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/automat/controlkit.js@master/bin/controlKit.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/locomotive-scroll@3.5.4/dist/locomotive-scroll.min.js"></script>
    <script  type="text/javascript"  src="https://unpkg.com/sheryjs/dist/Shery.js"></script> 
    <script src="script.js"></script>

**Comment by asynchronousJavascriptor** [comment]
we're creating a v2 it's in development currently, almost every issue related to it will be resolved <3
